---
name: deployments

on:
  push:

jobs:
  deployments:
    name:  Environment deployments
    strategy:
      matrix:
        envs:  [dev, qa, preprod]
    runs-on: ubuntu-latest
    steps:
      - name: output Environment
        run: echo Hello from ${{ matrix.envs }}


