---
name: deployments

on:
  push:

jobs:
  deployments:
    name:  Environment deployments
    strategy:
      matrix:
        env:  [dev, qa, preprod]
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    steps:
      - name: output Environment
        run: echo Hello from ${{ matrix.env }}

