---
name: deployments

on:
  push:

jobs:
  deployments:
    name:  Environment deployments
    strategy:
      matrix:
        include:
          - gh_env: dev
            namespace: test_dev
            tag: ${{ github.sha }}
            strategy: none
          - gh_env: qa
            namespace: test_qa            
            tag: ${{ github.sha }}
            strategy: qa-auto
          - gh_env: preprod
            namespace: test_dev
            tag: ${{ github.sha }}
            strategy: uat-validation


    runs-on: ubuntu-latest
    environment: ${{ matrix.gh_env }}
    steps:
      - name: output Environment
        run: | 
          echo "Hello from ${{ matrix.gh_env }}"
          echo "Using AWS Namesspace ${{ matrix.namespace }} and tag ${{ matrix.tag }} via strategy ${{ matrix.strategy }}"

